# Generated by Django 5.2.3 on 2025-07-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('background', models.TextField(blank=True)),
                ('visibility', models.CharField(default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('background', models.TextField(blank=True)),
                ('visibility', models.CharField(default='private', max_length=20)),
                ('status', models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], default='doing', max_length=10)),
                ('listid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.list')),
            ],
        ),
    ]
